name: Build LaTeX documents

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile abstract
        uses: xu-cheng/latex-action@v2
        with:
          root_file: DLT20201-abstract.tex
      - name: Compile slides
        uses: xu-cheng/latex-action@v2
        with:
          root_file: DLT2021-slides.tex
      - name: Check pdf files
        run: |
          file DLT2021-abstract.pdf | grep -q ' PDF '
          file DLT2021-slides.pdf | grep -q ' PDF '
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: DLT2021
          path: |
            DLT2021-abstract.pdf
            DLT2021-slides.pdf
        if: always()
